In [32]:
!pip install numpy

In [33]:
import numpy as np

In [34]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [35]:
a = np.array([1, 2, 4, 5, 6])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])

[1 2 3 4]


In [36]:
import numpy as np
a = np.array([1, 2, 3])
np.zeros(2)

array([0., 0.])

In [37]:
np.ones(2)

array([1., 1.])

In [38]:
np.empty(2)

array([1., 1.])

In [39]:
np.arange(4)


array([0, 1, 2, 3])

In [40]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [41]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [43]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])
array_example.ndim

3

In [48]:
array_example.size

24

In [49]:
array_example.shape

(3, 2, 4)

In [50]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [53]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [54]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [55]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [56]:
a2 = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [57]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [59]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [60]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [61]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [62]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [63]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [64]:
data = np.array([1, 2, 3])
data[1]

2

In [65]:
data[0:2]

array([1, 2])

In [66]:
data[1:]

array([2, 3])

In [67]:
data[-2:]

array([2, 3])

In [68]:
a = np.full((5, 7), 0.5)
a

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [73]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]
